### ISSUE TITLE
incorrect dependency type

### ISSUE THREAD

**Issue by chorny** [ePages-de/Mockify#24]
Minilla is listed as 'build' dependency in cpanfile. If it is not used in module installation, it should be listed as 'develop'. See https://metacpan.org/pod/CPAN::Meta::Spec#Phases

Same for Devel::Cover and other modules.

**Comment by chorny** [comment]
And CPAN::Uploader in basic requires category.

**Comment by ChristianBreitkreutz** [comment]
Good point, I will have a look. Thanks!

**Comment by ChristianBreitkreutz** [comment]
done
